// Auto-generated by ContGenerator

export const categories = [
  {
    "name": "Example Category",
    "slug": "example-category",
    "count": 1
  }
];

export const articles = [
  {
    "title": "Un test generico",
    "slug": "un-test-generico",
    "keyword": "prueba-generica",
    "content": "Introducción\nEste es un parrafo de prueba generica que tiene algunas palabras para ver si el contador de palabras y el formateo de tiempo funciona adecuadamente en este generador super avanzado sin ataduras. \n\n1. El formato de listas\nEsto tiene que pasar.",
    "excerpt": "Este es un parrafo de prueba generica que tiene algunas palabras para ver si el contador de palabras y el formateo de tiempo funciona adecuadamente en este generador super avanzado sin ataduras....",
    "readTime": "1 min de lectura",
    "wordCount": 42,
    "category": "Example Category",
    "categorySlug": "example-category",
    "date": "2026-04-24",
    "image": "img1.jpg"
  }
];
