const fs = require('fs');
const path = require('path');

// Helper Functions
function slugify(text) {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .substring(0, 80)
    .replace(/-$/, "");
}

function calculateReadTime(text) {
  const wordsPerMinute = 200;
  const words = text.split(/\s+/).length;
  const minutes = Math.ceil(words / wordsPerMinute);
  return `${minutes} min de lectura`;
}

function countWords(text) {
  return text.split(/\s+/).filter((w) => w.length > 0).length;
}

// Format Parsers
function parseFormatA(content, categoryName, categorySlug, configImages, indexCounter) {
  const articleRegex = /^(\d+)\.\s+(.+?)\r?\nKeyword Principal:\s*(.+?)$/gm;
  const matches = [...content.matchAll(articleRegex)];
  const articles = [];

  for (let i = 0; i < matches.length; i++) {
    const match = matches[i];
    const title = match[2].trim();
    const keyword = match[3].trim();
    const startPos = match.index + match[0].length;
    const endPos = i + 1 < matches.length ? matches[i + 1].index : content.length;
    let articleContent = content.substring(startPos, endPos).trim();

    const ctaIndex = articleContent.indexOf("CTA");
    if (ctaIndex > -1) {
      articleContent = articleContent.substring(0, ctaIndex).trim();
    }

    articleContent = articleContent
      .replace(/\r/g, "")
      .replace(/^\* /gm, "- ")
      .replace(/\[Insertar.*?\]/g, "")
      .replace(/\n{3,}/g, "\n\n")
      .trim();

    const excerptText = articleContent.replace(/^Introducci[oó]n\s*/i, "");
    const excerpt = excerptText.split("\n")[0].substring(0, 200).replace(/\s+/g, " ").trim() + "...";
    
    // Select image
    const images = configImages || [];
    const image = images.length > 0 ? images[indexCounter.val++ % images.length] : "";

    articles.push({
      title,
      slug: slugify(title),
      keyword,
      content: articleContent,
      excerpt,
      readTime: calculateReadTime(articleContent),
      wordCount: countWords(articleContent),
      category: categoryName,
      categorySlug,
      date: new Date().toISOString().split("T")[0],
      image
    });
  }
  return articles;
}

// Main execution function
function buildContent(configPath) {
  console.log(`[ContGenerator] Starting build using config: ${configPath}`);
  
  if (!fs.existsSync(configPath)) {
    console.error(`[Error] Configuration file not found at ${configPath}`);
    process.exit(1);
  }

  const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  const contentDir = path.resolve(process.cwd(), config.contentDir || "content");
  const outputFile = path.resolve(process.cwd(), config.outputFile || "data.json");
  
  if (!fs.existsSync(contentDir)) {
    console.error(`[Error] Content directory not found at ${contentDir}`);
    process.exit(1);
  }

  const files = fs.readdirSync(contentDir).filter(f => f.endsWith('.txt'));
  let allArticles = [];
  const generatedCategories = [];
  const indexCounter = { val: 0 };

  for (const file of files) {
    const slug = file.replace('.txt', '');
    const categoryConfig = config.categories.find(c => c.id === slug);
    
    if (!categoryConfig) {
      console.warn(`[Warning] No category config found for ${file}. Skipping.`);
      continue;
    }

    const content = fs.readFileSync(path.join(contentDir, file), 'utf8');
    const articles = parseFormatA(content, categoryConfig.name, slug, categoryConfig.images, indexCounter);
    
    allArticles = allArticles.concat(articles);
    generatedCategories.push({
      name: categoryConfig.name,
      slug: slug,
      count: articles.length
    });
  }

  // Generate output structure
  const outputData = {
    categories: generatedCategories,
    articles: allArticles
  };

  // Write output
  const outDir = path.dirname(outputFile);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  if (outputFile.endsWith('.ts')) {
    const tsContent = `// Auto-generated by ContGenerator\n\nexport const categories = ${JSON.stringify(outputData.categories, null, 2)};\n\nexport const articles = ${JSON.stringify(outputData.articles, null, 2)};\n`;
    fs.writeFileSync(outputFile, tsContent);
  } else {
    fs.writeFileSync(outputFile, JSON.stringify(outputData, null, 2));
  }

  console.log(`[Success] Parsed ${allArticles.length} articles into ${outputFile}`);
}

module.exports = { buildContent };
